module.exports = {
    RAZORPAY_KEY_SECRET: process.env.RAZORPAY_KEY_SECRET,
    RAZORPAY_WEB_CALLBACK_URL: process.env.RAZORPAY_WEB_CALLBACK_URL,
    RAZORPAY_APP_CALLBACK_URL: process.env.RAZORPAY_APP_CALLBACK_URL,
    RAZORPAY_CALLBACK_METHOD: process.env.RAZORPAY_CALLBACK_METHOD,
    RAZORPAY_KEY_ID: process.env.RAZORPAY_KEY_ID,
    RAZORPAY_SECRET: process.env.RAZORPAY_SECRET,
    RAZORPAY_LINK_EXPIRY_TIME: process.env.RAZORPAY_LINK_EXPIRY_TIME
};
  